import { load } from 'js-yaml';

console.log('Generating resume data module...');

// Read and parse the YAML file
const yamlText = await Bun.file("./data/resume_tailored.yaml").text();
const resumeData = load(yamlText);

// Generate TypeScript module
const tsContent = `// Auto-generated resume data from YAML
// Do not edit this file directly - edit data/resume_tailored.yaml instead

export default ${JSON.stringify(resumeData, null, 2)} as const;
`;

// Write the generated module
await Bun.write("./src/data/resume.ts", tsContent);

console.log('Resume data module generated successfully at ./src/data/resume.ts');