// Auto-generated resume data from YAML
// Do not edit this file directly - edit data/resume_tailored.yaml instead

export default {
  "resume": {
    "name": "Javiera Vasquez",
    "profile_picture": "/images/avatar.webp",
    "title": "Senior Frontend Engineer",
    "summary": "Experienced Frontend Developer with over a decade of experience, specializing in crafting user-centric applications using modern stacks like React, React Native, Node, and TypeScript. with real world experience developing Web and Mobile experience for multinational markets focusing on delivering software quality through Test Automation, Events Tracking and CI/CD pipelines, ensuring robust and reliable digital solutions. Extensive experience in debugging, optimizing user experiences and fostering collaboration within cross-functional teams and C level executives in fast pacing startups.",
    "contact": {
      "phone": "+49 1590 1070292",
      "email": "Javiera.vasg@gmail.com",
      "address": "Elsenstrasse 61, 12059 - Berlin, Germany",
      "linkedin": "https://www.linkedin.com/in/javiera-vasquez-94523960/",
      "github": "https://github.com/javiera-vasquez"
    },
    "technical_expertise": [
      {
        "resume_title": "Frontend Development",
        "skills": [
          "React",
          "TypeScript",
          "React Native",
          "Next.js",
          "Redux",
          "React Query",
          "GraphQL",
          "CSS"
        ]
      },
      {
        "resume_title": "Quality Assurance & Testing",
        "skills": [
          "E2E Testing (Playwright, Selenium)",
          "Jest",
          "CI/CD Pipelines",
          "Test Coverage",
          "Performance Optimization",
          "Regression Testing"
        ]
      },
      {
        "resume_title": "Backend Development",
        "skills": [
          "Node.js",
          "SQL/NoSQL",
          "Firebase",
          "Apollo Client"
        ]
      },
      {
        "resume_title": "Systems & Architecture",
        "skills": [
          "Scalable Architecture",
          "Real-Time Synchronization",
          "CI/CD Pipelines"
        ]
      }
    ],
    "skills": [
      "Problem-Solving",
      "Analytical Thinking",
      "User-Centric Approach",
      "Cross-functional Collaboration",
      "Team Collaboration",
      "Technical Mentorship",
      "Communication with C-Level",
      "Agile Development",
      "Strategic Thinking",
      "Data-Driven Decision Making",
      "Product-Oriented Mindset",
      "Pattern Recognition & System Design"
    ],
    "languages": [
      {
        "language": "Spanish",
        "proficiency": "Native"
      },
      {
        "language": "English",
        "proficiency": "C2"
      },
      {
        "language": "German",
        "proficiency": "B2"
      }
    ],
    "professional_experience": [
      {
        "company": "German studies",
        "position": "Sabbatical",
        "location": "Berlin, Germany",
        "duration": "May 2024 - May 2025",
        "company_description": "When from A2 to B2, plus the required certification in one year, reaching conversation level of German in less than one year of study an less than 3 years of leaving in Germany.",
        "linkedin": null,
        "achievements": []
      },
      {
        "company": "Inkitt",
        "position": "Senior Frontend Engineer",
        "location": "Berlin, Germany - United States",
        "duration": "March 2021 - April 2024",
        "company_description": "Inkitt is revolutionizing publishing through data-driven strategies and AI-powered tools to discover hidden literary talents and bring their stories to millions of users through platforms like Galatea #7 ranking in the Books category on the Apple App Store in Germany.",
        "linkedin": "https://www.linkedin.com/company/inkitt",
        "achievements": [
          "Led the migration and redesign of core Library Feature, one of Galatea's principal user experiences",
          "Improved application performance by 15% through strategic frontend optimization",
          "Built scalable React-based components serving millions of daily active users",
          "Implemented data-driven UI improvements that increased user engagement",
          "Mentored team members on modern frontend development practices"
        ]
      },
      {
        "company": "Alba Care",
        "position": "Senior Frontend Engineer",
        "location": "United States, Remote",
        "duration": "January 2019 - March 2021",
        "company_description": "Alba Care provides a digital marketplace app for home-based childcare, delivering seamless user experiences for parents and caregivers.",
        "linkedin": "https://www.linkedin.com/company/zebrands/",
        "achievements": [
          "Architected and led implementation of unified GraphQL layer, tripling mobile app performance",
          "Led the transition from traditional API structures to GraphQL for real-time data flow",
          "Built and maintained B2C App using React Native with user-friendly interface and robust functionality",
          "Led a pod of 2 Frontend developers and 1 product designer, shipping features bi-weekly",
          "Delivered seamless user experiences for both parents and caregivers across platforms"
        ]
      },
      {
        "company": "Cornershop by Uber",
        "position": "Senior Frontend Engineer",
        "location": "Santiago, Chile",
        "duration": "May 2016 - January 2019",
        "company_description": "Cornershop is a last-mile marketplace offering on-demand grocery delivery services across the Americas, now part of Uber.",
        "linkedin": "https://www.linkedin.com/company/cornershop-by-uber/",
        "achievements": [
          "Migrated 1.2M users from AngularJS to React SPA with zero downtime",
          "Led complete B2C web app migration improving scalability, modularity, and maintainability",
          "Built real-time shopping cart synchronization system serving 8 countries using Firebase",
          "Introduced cross-platform integration enabling shopping cart sync between user devices",
          "Delivered scalable frontend architecture supporting rapid international expansion"
        ]
      },
      {
        "company": "VTR Liberty Global",
        "position": "Frontend Engineer",
        "location": "Santiago, Chile",
        "duration": "December 2014 - April 2016",
        "company_description": "VTR is a leading telecom provider in Chile, offering TV, internet, and phone services to over 2.5 million homes.",
        "linkedin": "https://www.linkedin.com/company/vtr/",
        "achievements": [
          "Developed Video-on-Demand platform bringing Netflix-like capabilities to legacy TV decoders",
          "Created comprehensive design system standardizing UI across web platforms for B2C and B2B",
          "Built scalable frontend architecture serving 750K home devices",
          "Delivered modern streaming experience on legacy hardware infrastructure"
        ]
      }
    ],
    "independent_projects": [
      {
        "name": "Seeker - AI-Powered Conversational Search Platform",
        "location": "Berlin, Germany",
        "duration": "May 2024 - Present",
        "description": "A self-directed deep dive to master the new AI paradigm, resulting in a production-ready conversational interface for video discovery.",
        "url": "https://doug-langgraph-app-production.up.railway.app/search/new",
        "achievements": [
          "Built a conversational AI interface that transforms how users explore video content through natural language chat, visual discovery cards, and intelligent context management across multi-turn conversations",
          "Achieved breakthrough economics: $0.003 per AI query cost by optimizing token-per-turn interactions and context management",
          "Built production-ready platform with React frontend and vector database backend, achieving ~0.7s first token response time",
          "Solved the 'invisible content' problem by processing and indexing 4,9k+ video segments (113+ hours), making them searchable by meaning",
          "Designed architecture that demonstrates how to leverage AI intelligently in frontend applications for maximum impact"
        ],
        "impact": "This deep understanding now enables me to architect frontends that leverage AI intelligently—knowing exactly when and how to use it to maximize user impact while maintaining cost efficiency"
      }
    ],
    "education": [
      {
        "institution": "Stanford University",
        "program": "CS161 Design and Analysis of Algorithms",
        "location": "Remote learning",
        "duration": "2014 - 2014"
      },
      {
        "institution": "Harvard",
        "program": "CS50's Introduction to Computer Science",
        "location": "Remote learning",
        "duration": "2012 - 2012"
      },
      {
        "institution": "DUOC UC",
        "program": "Bachelor of Design - Advertising and Graphic Design",
        "location": "Santiago, Chile",
        "duration": "2008 - 2010"
      }
    ]
  },
  "job_analysis": {
    "focus_area": "frontend_focused",
    "job_title": "Senior Frontend Engineer - React",
    "company": "Veeva Systems",
    "location": "Berlin, Germany (Remote Available)",
    "key_requirements": [
      "4+ years professional web application development",
      "React or comparable JavaScript framework experience",
      "Experience developing products in agile environment",
      "UI/UX design principles knowledge",
      "Strong testing, debugging, documentation skills",
      "TypeScript experience",
      "AWS and MongoDB knowledge",
      "State management tools (TanStack Query, MobX, Redux)",
      "Cloud technology stack experience",
      "Autonomous work style"
    ],
    "transformation_decisions": "Selected frontend_focused version to align with pure frontend role requirements.\nPrioritized technical expertise categories: Frontend Development, QA & Testing, Backend, Systems Architecture.\nEmphasized React, TypeScript, testing, and scalable architecture experience.\nHighlighted achievements demonstrating scalable web application development, performance optimization, and team leadership.\nSelected experiences showing migration expertise, real-time systems, and million-user scale applications.\n",
    "match_strength": "Excellent",
    "key_alignments": [
      "10+ years frontend experience exceeds 4+ year requirement",
      "Extensive React expertise across multiple companies",
      "Berlin location matches perfectly",
      "Strong TypeScript, testing, and debugging background",
      "Experience with state management (Redux, React Query)",
      "Proven track record building scalable applications for millions of users",
      "Leadership and mentoring experience",
      "Agile development methodology throughout career"
    ],
    "potential_concerns": [
      "Limited direct AWS experience mentioned",
      "MongoDB experience not explicitly detailed",
      "Healthcare/life sciences domain experience not present"
    ]
  }
} as const;
